# postgresql DataBase
spring:
  datasource:
    hikari:
      schema:
    url:
    username:
    password:
    driver-class-name:
  ai:
    openai:
      api-key:
datasource:
  source:
    url:
    username:
    password:
    driver-class-name:
  target:
    url:
    username:
    password:
    driver-class-name: 